Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -101,14 +101,26 @@ jobs:
           curl -L -o /usr/local/bin/sl https://cdn.shiftleft.io/download/sl
           chmod a+rx /usr/local/bin/sl
 
-      - name: Run ShiftLeft Scan Action
+      - name: Run ShiftLeft Scan
+        id: scan
         uses: ShiftLeftSecurity/scan-action@master
         with:
           type: "credscan,java,depscan"
         env:
           SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
           SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
-          SHIFTLEFT_API_TOKEN: ${{ secrets.SHIFTLEFT_API_TOKEN }} 
+          SHIFTLEFT_API_TOKEN: ${{ secrets.SHIFTLEFT_API_TOKEN }}
+
+      - name: Upload ShiftLeft Report
+        if: failure()  # Only runs if the previous step fails
+        run: |
+          # Check if the report file exists and display its contents
+          if [ -f shiftleft-report.sarif ]; then
+            cat shiftleft-report.sarif
+            echo "ShiftLeft scan failed with exit code $?"
+          else
+            echo "ShiftLeft report not found."
+          fi 
 
       - name: Upload ShiftLeft Scan Report
         uses: actions/upload-artifact@v3
